"""
Django settings for Pomelo_test project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = ['*']
# http自動轉https
# SECURE_SSL_REDIRECT = True
# CSRF_COOKIE_DOMAIN = None

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 60 * 10

CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_CREDENTIALS = True


CSRF_TRUSTED_ORIGINS = ['https://front.bluemix.net/']

CORS_REPLACE_HTTPS_REFERER = True

CSRF_COOKIE_DOMAIN = 'bluemix.net'

CORS_ORIGIN_WHITELIST = (
    'https://front.bluemix.net/',
    'front.bluemix.net',
    'bluemix.net',
)

# Application definition
# 網站後台功能登錄區域設定
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'whitenoise.runserver_nostatic',
    'Pomelo_API',
    "sslserver",
    "specialty_medical",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware',
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'ERROR',
    }
}

ROOT_URLCONF = 'Pomelo_test.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'Public', 'html')],  #讓 server 找得到 html 的位置
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'specialty_medical.context_processors.default_tracking_ids', # 共用 GA、GTM 設定於 context_processors.py
            ],
        },
    },
]

WSGI_APPLICATION = 'Pomelo_test.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
MEDIA_URL = '/media/'   # MEDIA 是放上傳/下載檔案用
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  #絕對路徑；os.path-指路徑導向的副函數
SITE_DOMAIN = "https://web.everanhospital.com.tw" #Site Domain (固定給 og:url / og:image 用)
STATIC_URL = '/Public/'   # STATIC 放置所有靜態檔，例 css/js/ html
if (DEBUG == False):
    #STATIC_ROOT = os.path.join(BASE_DIR, 'Public')   # 正式區需帶語法 r 代表可把檔案路徑改成文字，所以可直接複製路徑貼上就好
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'Public'),os.path.join(BASE_DIR, 'media'),]
else:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'Public'),os.path.join(BASE_DIR, 'media'),]  # 測試區需帶這個語法，才吃得到 js/css 資料夾

# STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# External Database Configuration
# Oracle
CASE_PLSQL_HOST = os.getenv('CASE_PLSQL_HOST')
CASE_PLSQL_DB = os.getenv('CASE_PLSQL_DB')
CASE_PLSQL_USER = os.getenv('CASE_PLSQL_USER')
CASE_PLSQL_PWD = os.getenv('CASE_PLSQL_PWD')

# MSSQL 66.146
MSSQL_66_146_HOST = os.getenv('MSSQL_66_146_HOST')
MSSQL_66_146_DB = os.getenv('MSSQL_66_146_DB')
MSSQL_66_146_USER = os.getenv('MSSQL_66_146_USER')
MSSQL_66_146_PWD = os.getenv('MSSQL_66_146_PWD')

# MSSQL 66.147
MSSQL_66_147_HOST = os.getenv('MSSQL_66_147_HOST')
MSSQL_66_147_DB = os.getenv('MSSQL_66_147_DB')
MSSQL_66_147_USER = os.getenv('MSSQL_66_147_USER')
MSSQL_66_147_PWD = os.getenv('MSSQL_66_147_PWD')

# MSSQL 200.211
MSSQL_200_211_HOST = os.getenv('MSSQL_200_211_HOST')
MSSQL_200_211_DB = os.getenv('MSSQL_200_211_DB')
MSSQL_200_211_USER = os.getenv('MSSQL_200_211_USER')
MSSQL_200_211_PWD = os.getenv('MSSQL_200_211_PWD')

# MSSQL 51.45 (A101)
MSSQL_51_45_HOST = os.getenv('MSSQL_51_45_HOST')
MSSQL_51_45_DB = os.getenv('MSSQL_51_45_DB')
MSSQL_51_45_USER = os.getenv('MSSQL_51_45_USER')
MSSQL_51_45_PWD = os.getenv('MSSQL_51_45_PWD')

# MSSQL 66.149
MSSQL_66_149_HOST = os.getenv('MSSQL_66_149_HOST')
MSSQL_66_149_DB = os.getenv('MSSQL_66_149_DB')
MSSQL_66_149_USER = os.getenv('MSSQL_66_149_USER')
MSSQL_66_149_PWD = os.getenv('MSSQL_66_149_PWD')

# Email Settings
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT', 25)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS') == 'True'
