"""
Django settings for Pomelo_test project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

SITE_ID = 1

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = ['*']
# http自動轉https
# SECURE_SSL_REDIRECT = True
# CSRF_COOKIE_DOMAIN = None

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 60 * 10

# CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_CREDENTIALS = True


# CSRF_TRUSTED_ORIGINS = ['https://front.bluemix.net/']
CSRF_TRUSTED_ORIGINS = [
	# 'https://front.bluemix.net',
	'https://web.everanhospital.com.tw',
]

CORS_REPLACE_HTTPS_REFERER = True

# CSRF_COOKIE_DOMAIN = 'bluemix.net'

# 跨域驗證，如果是 http、或開發環境 就設 False
if DEBUG == True:
	CSRF_COOKIE_SECURE = False
	SESSION_COOKIE_SECURE = False
else:
	CSRF_COOKIE_SECURE = True
	SESSION_COOKIE_SECURE = True

# 改為依 DEBUG 或環境決定（本機開發不設定 domain）
	CSRF_COOKIE_DOMAIN = None

# 若使用 Nginx 轉發 HTTPS，需加上此設定告知 Django 來源為 HTTPS
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CORS_ORIGIN_WHITELIST = (
#     'https://front.bluemix.net/',
#     'front.bluemix.net',
#     'bluemix.net',
# )


# Application definition
# 網站後台功能登錄區域設定
INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'whitenoise.runserver_nostatic',
	'django.contrib.staticfiles',
	'django.contrib.sitemaps',
	'django.contrib.sites',
	'Pomelo_API',
	"sslserver",
	"specialty_medical",
	"specialty_health",
	"EECP",
	"Breast_Care_Center",
	"Neurology_Center",
	"cardio_center",
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'whitenoise.middleware.WhiteNoiseMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

LOGGING = {
	'version': 1,
	'disable_existing_loggers': False,
	'handlers': {
		'console': {
			'class': 'logging.StreamHandler',
		},
	},
	'root': {
		'handlers': ['console'],
		'level': 'ERROR',
	}
}

ROOT_URLCONF = 'Pomelo_test.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		# 修改前
		# 'DIRS': [os.path.join(BASE_DIR, 'Public', 'html')],  # 讓 server 找得到 html 的位置
		# 修改後: 指向新的 templates 目錄
		'DIRS': [os.path.join(BASE_DIR, 'templates')],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.template.context_processors.media',
				'django.contrib.messages.context_processors.messages',
				# GA, GTM, og-image, breadcrumb 設定於 context_processors.py
				'Pomelo_test.context_processors.default_tracking_ids',
				'Pomelo_test.context_processors.breadcrumb_processor'
			],
		},
	},
]

WSGI_APPLICATION = 'Pomelo_test.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': BASE_DIR / 'db.sqlite3',
	}
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
MEDIA_URL = '/media/'   # MEDIA 是放上傳/下載檔案用
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 絕對路徑;os.path-指路徑導向的副函數
SITE_DOMAIN = "https://web.everanhospital.com.tw" # Site Domain (固定給 og:url / og:image 用)
STATIC_URL = '/Public/'   # STATIC 放置所有靜態檔，例 css/js/ html

# 設定 collectstatic 收集目的地 (Nginx 指向這裡)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

if DEBUG:
	# === [開發模式] ===
	# 請根據您的啟動方式，選擇保留一個區塊，並註解掉另一個。

	# [模式 A] 使用 python manage.py runserver 啟動 (預設)
	# 特點：不需要 Nginx，Django 會自動處理靜態檔與媒體檔。
	# 為了讓開發時能看到 /Public/ 下的媒體圖片，這裡把 media 也加入搜尋路徑。
	# STATICFILES_DIRS = [
	#     os.path.join(BASE_DIR, 'Public'),
	#     os.path.join(BASE_DIR, 'media'),
	# ]

	# [模式 B] 使用 Nginx + Django 啟動
	# 特點：模擬正式環境，靜態檔由 Nginx 處理。
	# 執行 collectstatic 時不應該包含 media，以免複製大量圖片。
	# 若要使用此模式，請打開下方註解，並註解掉上方 [模式 A]
	STATICFILES_DIRS = [
		os.path.join(BASE_DIR, 'Public'),
	]

else:
	# === [正式/模擬正式模式] (DEBUG=False) ===
	# 必須使用 Nginx + collectstatic
	STATICFILES_DIRS = [
		os.path.join(BASE_DIR, 'Public'),
	]

# 針對靜態檔案做壓縮、打包（Brotli/Gzip）與雜湊值機制(效能優化)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# External Database Configuration
# Oracle
CASE_PLSQL_HOST = os.getenv('CASE_PLSQL_HOST')
CASE_PLSQL_DB = os.getenv('CASE_PLSQL_DB')
CASE_PLSQL_USER = os.getenv('CASE_PLSQL_USER')
CASE_PLSQL_PWD = os.getenv('CASE_PLSQL_PWD')

# Oracle Client Path (for Thick Mode)
ORACLE_CLIENT_PATH = os.getenv('ORACLE_CLIENT_PATH')

# MSSQL 66.146
MSSQL_66_146_HOST = os.getenv('MSSQL_66_146_HOST')
MSSQL_66_146_DB = os.getenv('MSSQL_66_146_DB')
MSSQL_66_146_USER = os.getenv('MSSQL_66_146_USER')
MSSQL_66_146_PWD = os.getenv('MSSQL_66_146_PWD')

# MSSQL 66.147
MSSQL_66_147_HOST = os.getenv('MSSQL_66_147_HOST')
MSSQL_66_147_DB = os.getenv('MSSQL_66_147_DB')
MSSQL_66_147_USER = os.getenv('MSSQL_66_147_USER')
MSSQL_66_147_PWD = os.getenv('MSSQL_66_147_PWD')

# MSSQL 200.211
MSSQL_200_211_HOST = os.getenv('MSSQL_200_211_HOST')
MSSQL_200_211_DB = os.getenv('MSSQL_200_211_DB')
MSSQL_200_211_USER = os.getenv('MSSQL_200_211_USER')
MSSQL_200_211_PWD = os.getenv('MSSQL_200_211_PWD')

# MSSQL 51.45 (A101)
MSSQL_51_45_HOST = os.getenv('MSSQL_51_45_HOST')
MSSQL_51_45_DB = os.getenv('MSSQL_51_45_DB')
MSSQL_51_45_USER = os.getenv('MSSQL_51_45_USER')
MSSQL_51_45_PWD = os.getenv('MSSQL_51_45_PWD')

# MSSQL 66.149
MSSQL_66_149_HOST = os.getenv('MSSQL_66_149_HOST')
MSSQL_66_149_DB = os.getenv('MSSQL_66_149_DB')
MSSQL_66_149_USER = os.getenv('MSSQL_66_149_USER')
MSSQL_66_149_PWD = os.getenv('MSSQL_66_149_PWD')

# Email Settings
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT', 25)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS') == 'True'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Send-Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'mail.everanhospital.com.tw') # SMTP 伺服器位址 (預設值僅供參考，應使用 .env)
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True' # 根據伺服器設定
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 25)) # SMTP 伺服器連接埠
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER') # 使用者名稱
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD') # 密碼
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER) # 寄件者信箱

# 新增：讀取通知信收件者，並轉為 List（共用預設，各服務未設定時使用）
NOTIFY_EMAIL_RECIPIENTS = os.getenv('NOTIFY_EMAIL_RECIPIENTS', '').split(',')
NOTIFY_EMAIL_RECIPIENTS = [email.strip() for email in NOTIFY_EMAIL_RECIPIENTS if email.strip()]

def _parse_contact_recipients(env_key, default_list):
	"""從 env 讀取逗號分隔的收件信箱，若為空則回傳 default_list"""
	raw = os.getenv(env_key, '').strip()
	if not raw:
		return default_list
	return [email.strip() for email in raw.split(',') if email.strip()]

# 各服務聯絡我們收件信箱（可多個，逗號分隔）
CONTACT_EMAIL_RECIPIENTS_EECP = _parse_contact_recipients('CONTACT_EMAIL_RECIPIENTS_EECP', NOTIFY_EMAIL_RECIPIENTS)
CONTACT_EMAIL_RECIPIENTS_HEALTH = _parse_contact_recipients('CONTACT_EMAIL_RECIPIENTS_HEALTH', NOTIFY_EMAIL_RECIPIENTS)  # 健管中心
CONTACT_EMAIL_RECIPIENTS_BREAST = _parse_contact_recipients('CONTACT_EMAIL_RECIPIENTS_BREAST', NOTIFY_EMAIL_RECIPIENTS)   # 乳房中心
CONTACT_EMAIL_RECIPIENTS_MAIN = _parse_contact_recipients('CONTACT_EMAIL_RECIPIENTS_MAIN', NOTIFY_EMAIL_RECIPIENTS)     # 主站意見反映
CONTACT_EMAIL_RECIPIENTS_ORT = _parse_contact_recipients('CONTACT_EMAIL_RECIPIENTS_ORT', NOTIFY_EMAIL_RECIPIENTS)       # 骨科微創手術中心
CONTACT_EMAIL_RECIPIENTS_NEURO = _parse_contact_recipients('CONTACT_EMAIL_RECIPIENTS_NEURO', NOTIFY_EMAIL_RECIPIENTS)       # 神經醫學中心
CONTACT_EMAIL_RECIPIENTS_CARDIO = _parse_contact_recipients('CONTACT_EMAIL_RECIPIENTS_CARDIO', NOTIFY_EMAIL_RECIPIENTS)       # 心血管中心